def log_iterates(problem, x, stats):
    """
    This small helper function is used to log the sequence of iterates
    generated by the Riemannian Staircase

    :param problem: Manopt problem
    :param x: Current iterate
    :param stats: Dictionary containing stats information
    :return: Updated stats dictionary with iterates logged
    """
    stats["Yvals"] = x.T
    return stats